import { signal } from '@preact/signals';

const getInitialLang = () => {
  try {
    return localStorage.getItem('lang') || 'EN';
  } catch (e) {
    return 'EN';
  }
};

const lang = signal(getInitialLang());

const translations = {
  EN: {
    home: 'Home',
    about: 'About',
    portfolio: 'Portfolio',
    articles: 'News',
    admin: 'Admin',
    heroTitle: 'Nomus',
    heroSubtitle: 'Film',
    heroTagline: "Write like a butterfly, film like a bee",
    heroDesc: 'Audiovisual Writing and Development. Based in Genova, Italy.',
    discover: 'Discover More',
    recentNews: 'Recent News',
    viewAll: 'View All',
    newsTitle: 'News',
    visionLabel: 'Vision',
    visionDesc: 'Exploring the balance between light and shadow in every frame.',
    storyTitle: 'Our Story',
    storySubtitle: 'Studio Nomus',
    storyDesc1: 'Studio Nomus is a writing and screenplay development studio founded in 2021 by Vinci Cardona and Nicolò Sanfilippo, two friends with a common goal: turning ideas into powerful and original narratives through a creative and collaborative approach.',
    storyDesc2: 'In May 2022, they joined Newness, the writing room founded by Alessandro Borghi and Guido Maria Brera. They recently completed development on the film "Il Domatore" (Groenlandia) and "Strangers" (Colorado Films). On the international front, they collaborate with London-based F.&.M.E. Ltd, developing projects across the UK, Germany, and Georgia.',
    servicesTitle: 'Our Services',
    service1: 'Writing of original treatments and screenplays',
    service2: 'Editing and revision of existing scripts',
    service3: 'Creative consultancy for narrative projects',
    service4: 'Workshops and masterclasses on story development',
    storyQuote: '"L\'essenziale è invisibile agli occhi, ma catturabile dall\'obiettivo."',
    visionaries: 'The Visionaries',
    bioVinci: 'Born in 1995, Vinci is a screenwriter and comic artist. In 2025, he won the Premio Mattador for the TV series "Bodycount".',
    bioNicolo: 'Born in 1995, Nicolò is a director and screenwriter. Associate Producer and Script Editor on the upcoming feature "Young Stalin".',
    portfolioTitle: 'Cinematic Portfolio',
    portfolioSubtitle: 'Fragments of time',
    portfolioPageTitle: 'Portfolio',
    portfolioPageSubtitle: "Author's Visions",
    portfolioEmpty: 'The showcase is being curated. Check back soon.',
    viewProject: 'View Project',
    newsPageTitle: 'Latest Insights',
    newsPageDesc: 'Thoughtful explorations into the world of cinema and audiovisual development.',
    readMore: 'Read Article',
    contentNotFound: 'Content not found',
    backToHome: 'Back to Home',
    noContent: 'No detailed content provided yet.',
    backToArticles: 'Back to Articles',
    backToPortfolio: 'Back to Portfolio',
    adminAccess: 'Admin Access',
    username: 'Username',
    password: 'Password',
    defaultPassword: 'Default Password',
    unlock: 'Unlock',
    initialLoginDesc: 'Initial login with default password',
    accountSetup: 'Account Setup',
    setupDesc: 'Please create your personalized credentials before continuing.',
    chooseUser: 'Choose Username',
    choosePass: 'Choose Password',
    finalizeSetup: 'Finalize Setup',
    logout: 'Logout',
    creatorStudio: 'Creator Studio',
    editDraft: 'Edit Draft',
    newStory: 'New Story',
    markdownGuide: 'Markdown Guide',
    title: 'Title',
    summary: 'Summary (Excerpt)',
    contentLabel: 'Markdown Content',
    category: 'Category',
    coverImage: 'Cover Image URL',
    publish: 'Publish to World',
    update: 'Update Story',
    cancel: 'Cancel',
    manageContent: 'Manage Content',
    searchPlaceholder: 'Search...',
    allTypes: 'All Types',
    newest: 'Newest',
    oldest: 'Oldest',
    byTitle: 'By Title',
    noMatches: 'No matches found for your search.',
    preview: 'Preview',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    saving: 'Saving...',
    success: 'Success!',
    error: 'Error.',
    uploading: 'Uploading...',
    uploaded: 'Uploaded!',
    footerLocation: 'Via San Siro 14r, Genova (GE)',
    builtWith: 'Built with Preact & Tailwind.',
    contact: 'Contact',
    contactTitle: 'Get in Touch',
    contactDesc: "Ready to tell your story? Reach out and let's create something extraordinary together.",
    emailLabel: 'Email Us',
    instagramLabel: 'Follow on Instagram',
    phoneLabel: 'Call Us',
    whatsappLabel: 'WhatsApp',
    partnersTitle: 'Our Partners',
    partnerType: 'Partner'
  },
  IT: {
    home: 'Home',
    about: 'Chi Siamo',
    portfolio: 'Portfolio',
    articles: 'Articoli',
    admin: 'Admin',
    heroTitle: 'Nomus',
    heroSubtitle: 'Film',
    heroTagline: "Scrivi come una farfalla, gira come un'ape",
    heroDesc: 'Scrittura e Sviluppo Audiovisivi. Sede a Genova, Italia.',
    discover: 'Scopri di Più',
    recentNews: 'Ultime Novità',
    viewAll: 'Vedi Tutto',
    newsTitle: 'News',
    visionLabel: 'Visione',
    visionDesc: 'Esplorare l\'equilibrio tra luce e ombra in ogni fotogramma.',
    storyTitle: 'La Nostra Storia',
    storySubtitle: 'Studio Nomus',
    storyDesc1: 'Studio Nomus è un laboratorio di scrittura e sviluppo sceneggiatura fondato nel 2021 da Vinci Cardona e Nicolò Sanfilippo, due professionisti con una visione condivisa: trasformare idee in narrazioni potenti e originali.',
    storyDesc2: 'Nel maggio 2022, sono entrati a far parte di Newness, la writing room fondata da Alessandro Borghi e Guido Maria Brera. Hanno recentemente concluso lo sviluppo del film "Il Domatore" e "Strangers". Collaborano stabilmente con la londinese F.&.M.E. ltd per progetti in UK, Germania e Georgia.',
    servicesTitle: 'I Nostri Servizi',
    service1: 'Scrittura di soggetti e sceneggiature originali',
    service2: 'Editing e revisione di script esistenti',
    service3: 'Consulenza creativa per progetti narrativi',
    service4: 'Workshop e masterclass sullo sviluppo di storie',
    storyQuote: '"L\'essenziale è invisibile agli occhi, ma catturabile dall\'obiettivo."',
    visionaries: 'I Visionari',
    bioVinci: 'Classe \'95, sceneggiatore e autore di fumetti. Nel 2025 ha vinto il Premio Mattador con la serie TV "Bodycount".',
    bioNicolo: 'Classe \'95, regista e sceneggiatore. Associate Producer e Script Editor sul lungometraggio "Young Stalin".',
    portfolioTitle: 'Portfolio Cinematografico',
    portfolioSubtitle: 'Frammenti di tempo',
    portfolioPageTitle: 'Portfolio',
    portfolioPageSubtitle: "Visioni d'autore",
    portfolioEmpty: 'La vetrina è in fase di cura. Torna presto.',
    viewProject: 'Visualizza Progetto',
    newsPageTitle: 'Ultime Notizie',
    newsPageDesc: 'Esplorazioni profonde nel mondo del cinema e dello sviluppo audiovisivo.',
    readMore: 'Leggi Articolo',
    contentNotFound: 'Contenuto non trovato',
    backToHome: 'Torna alla Home',
    noContent: 'Nessun contenuto dettagliato fornito.',
    backToArticles: 'Torna agli Articoli',
    backToPortfolio: 'Torna al Portfolio',
    adminAccess: 'Accesso Admin',
    username: 'Nome utente',
    password: 'Password',
    defaultPassword: 'Password Predefinita',
    unlock: 'Sblocca',
    initialLoginDesc: 'Primo accesso con password predefinita',
    accountSetup: 'Configurazione Account',
    setupDesc: 'Crea le tue credenziali personalizzate prima di continuare.',
    chooseUser: 'Scegli Username',
    choosePass: 'Scegli Password',
    finalizeSetup: 'Finalizza Configurazione',
    logout: 'Esci',
    creatorStudio: 'Creator Studio',
    editDraft: 'Modifica Bozza',
    newStory: 'Nuova Storia',
    markdownGuide: 'Guida Markdown',
    title: 'Titolo',
    summary: 'Riassunto (Estratto)',
    contentLabel: 'Contenuto Markdown',
    category: 'Categoria',
    coverImage: 'URL Immagine di Copertina',
    publish: 'Pubblica nel Mondo',
    update: 'Aggiorna Storia',
    cancel: 'Annulla',
    manageContent: 'Gestione Contenuti',
    searchPlaceholder: 'Cerca...',
    allTypes: 'Tutti i tipi',
    newest: 'Più recenti',
    oldest: 'Meno recenti',
    byTitle: 'Per Titolo',
    noMatches: 'Nessun risultato trovato.',
    preview: 'Anteprima',
    confirm: 'Conferma',
    delete: 'Elimina',
    edit: 'Modifica',
    saving: 'Salvataggio...',
    success: 'Successo!',
    error: 'Errore.',
    uploading: 'Caricamento...',
    uploaded: 'Caricato!',
    footerLocation: 'Via San Siro 14r, Genova (GE)',
    builtWith: 'Creato con Preact & Tailwind.',
    contact: 'Contatti',
    contactTitle: 'Mettiti in Contatto',
    contactDesc: "Pronto a raccontare la tua storia? Scrivici e creiamo insieme qualcosa di straordinario.",
    emailLabel: 'Scrivici',
    instagramLabel: 'Seguici su Instagram',
    phoneLabel: 'Chiamaci',
    whatsappLabel: 'WhatsApp',
    partnersTitle: 'I Nostri Partner',
    partnerType: 'Partner'
  }
};

export function useLanguage() {
  const toggleLang = () => {
    try {
      const next = lang.value === 'EN' ? 'IT' : 'EN';
      lang.value = next;
      localStorage.setItem('lang', next);
    } catch (e) {
      console.error('Failed to toggle language', e);
    }
  };

  const t = translations[lang.value] || translations['EN'];

  return { 
    lang, 
    t, 
    toggleLang 
  };
}
